# Generated by Django 2.2.7 on 2019-11-17 16:20

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [("dynamics", "0004_auto_20191015_0109")]

    operations = [
        migrations.AlterModelOptions(
            name="fuel", options={"ordering": ["name"], "verbose_name_plural": "fuels"}
        ),
        migrations.AlterModelOptions(
            name="pricehistory",
            options={
                "ordering": ["-at", "fuel", "currency"],
                "verbose_name_plural": "price history",
            },
        ),
        migrations.AddConstraint(
            model_name="pricehistory",
            constraint=models.UniqueConstraint(
                fields=("at", "currency", "price"), name="singular_price"
            ),
        ),
    ]
