# Generated by Django 2.2.6 on 2019-10-14 23:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("about", "0001_initial")]

    operations = [
        migrations.AlterModelOptions(
            name="technology",
            options={"ordering": ["name"], "verbose_name_plural": "technologies"},
        )
    ]
