# Generated by Django 2.2.7 on 2019-11-17 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("api", "0001_initial")]

    operations = [
        migrations.AlterModelOptions(
            name="apisettings",
            options={"ordering": ["user"], "verbose_name_plural": "API settings"},
        )
    ]
